//generated by ResBuilder in 2011//

#ifndef _LOGO_H_  
#define _LOGO_H_  

////StringResID Define Table////

#define  LANGUAGEID_SUM      0



////Multi Language Define Table////

#define  STRINGID_SUM      0



////BmpResID Define Table////
#define  JI           1
#define  JIE           2
#define  JIELIKEJI           3
#define  KE           4
#define  LI           5

#define  BMPID_SUM           5

#endif 
